services:
  - type: web
    name: pos-system
    runtime: docker
    plan: free
    rootDir: Web System Technologies/POS_System
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production
  - type: web
    name: electriccompany
    runtime: docker
    plan: free
    rootDir: Web System Technologies/electriccompany
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSL
        value: "true"
