services:
  - type: web
    name: pos-system
    runtime: docker
    plan: free
    rootDir: Web System Technologies/POS_System
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production
